on: [push, pull_request]
jobs:
  test:
    name: Test ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        arch: [ x86, x64 ]
        exclude:
          - os: windows-latest
            arch: x64
          - os: ubuntu-latest
            arch: x86
          # FIXME: temporarily disabled windows-latest x86 failing with:
          #        fatal error C1083: Cannot open include file: 'stdlib.h': No such file or directory
          - os: windows-latest
            arch: x86
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 2.7
          architecture: ${{ matrix.arch }}
      - name: Install dependencies
        run: python -m pip install pytest
      - name: Run tests
        run: python -m pytest -v -ra --color=yes assembler emulator
        env:
          PYTHONPATH: ./pypy
      - name: Run translation
        run: python pypy/rpython/bin/rpython emulator/chip8.py
        env:
          PYTHONPATH: .
      - name: Run app tests
        run: python -m pytest -v -ra --color=yes -A ./chip8-c emulator
        env:
          PYTHONPATH: ./pypy
